// Arduino demo sketch for the bearing-fault neural network on TFLM.
//
// Sketch folder must contain:
//     bearing_nn.ino           (this file)
//     bearing_inference.cc / bearing_inference.h
//     model_data.cc / model_data.h        (auto-generated by export_tflm.py)
//     model_settings.h                    (auto-generated by export_tflm.py)
//
// Install a TFLM library through the Library Manager, e.g.
// "Arduino_TensorFlowLite" or the maintained "Chirale_TensorFlowLite".
//
// In a real build you would replace get_demo_features() with the output of
// the time/frequency feature extractor in firmware/inference_stub.c, reading
// a window of accelerometer samples (e.g. MPU-6050) each cycle.

#include "bearing_inference.h"
#include "model_settings.h"

// A placeholder 22-feature vector (UNSCALED, in model_settings.h order).
// Replace with live features from your extractor.
static void get_demo_features(float* f) {
  for (int i = 0; i < kFeatureCount; ++i) f[i] = 0.0f;
}

void setup() {
  Serial.begin(115200);
  while (!Serial) {}

  if (bearing_nn_init() != 0) {
    Serial.println("TFLM init failed");
    while (true) {}
  }
  Serial.print("TFLM ready. Arena used: ");
  Serial.print(bearing_nn_arena_used());
  Serial.println(" bytes");
}

void loop() {
  float features[kFeatureCount];
  float probs[kCategoryCount];

  get_demo_features(features);

  const int cls = bearing_nn_classify(features, probs);
  if (cls < 0) {
    Serial.println("inference error");
  } else {
    Serial.print("Prediction: ");
    Serial.print(bearing_nn_label(cls));
    Serial.print("  [");
    for (int c = 0; c < kCategoryCount; ++c) {
      Serial.print(bearing_nn_label(c));
      Serial.print("=");
      Serial.print(probs[c], 3);
      if (c < kCategoryCount - 1) Serial.print(", ");
    }
    Serial.println("]");
  }
  delay(1000);
}
