// Auto-generated by src/models/export_tflm.py. Do not edit.
#ifndef TFLM_MODEL_SETTINGS_H_
#define TFLM_MODEL_SETTINGS_H_

constexpr int kFeatureCount = 22;
constexpr int kCategoryCount = 4;

// Tensor arena. This MLP needs only a few KB; tune downward if RAM
// is tight (the firmware prints interpreter.arena_used_bytes()).
constexpr int kTensorArenaSize = 8 * 1024;

// Class labels, indexed by the model's output channel.
inline const char* const kCategoryLabels[kCategoryCount] = {
    "Healthy",
    "Inner Race",
    "Outer Race",
    "Ball"
};

// StandardScaler parameters (fit on the training set). The device
// computes scaled[i] = (raw[i] - kFeatureMean[i]) / kFeatureScale[i]
// BEFORE quantizing and feeding the model. Feature order:
//   [ 0] rms
//   [ 1] mean
//   [ 2] variance
//   [ 3] std_dev
//   [ 4] kurtosis
//   [ 5] skewness
//   [ 6] peak
//   [ 7] peak_to_peak
//   [ 8] crest_factor
//   [ 9] shape_factor
//   [10] impulse_factor
//   [11] dominant_freq
//   [12] spectral_centroid
//   [13] spectral_spread
//   [14] band_energy_0_1k
//   [15] band_energy_1_3k
//   [16] band_energy_3_6k
//   [17] fft_peak_1
//   [18] fft_peak_2
//   [19] fft_peak_3
//   [20] spectral_entropy
//   [21] spectral_flatness
inline const float kFeatureMean[kFeatureCount] = {
    6.11283890e-01f, -4.40899528e-04f, 3.73623618e-01f, 6.11219735e-01f, 6.77537007e+00f, 3.48855185e-01f,
    3.11683572e+00f, 5.45483477e+00f, 5.09799668e+00f, 1.53413214e+00f, 7.88900441e+00f, 3.51562500e+01f,
    2.37719005e+03f, 1.68038109e+03f, 4.51405886e-01f, 1.43626179e-01f, 1.52496032e-01f, 4.46004203e-01f,
    4.14071214e-01f, 2.52525780e-01f, 4.23777017e-01f, 5.23442917e-01f,
};

inline const float kFeatureScale[kFeatureCount] = {
    5.91405698e-04f, 1.95379230e-04f, 7.20797351e-04f, 5.85818831e-04f, 1.83708041e+00f, 4.48249875e-01f,
    7.05784973e-01f, 1.19897092e+00f, 1.15484388e+00f, 6.32783199e-02f, 1.98602417e+00f, 1.00000000e+00f,
    1.65254395e+02f, 1.79737860e+02f, 1.68078900e-01f, 9.77691164e-02f, 7.79137964e-02f, 8.38237433e-02f,
    7.78332656e-02f, 2.61670124e-02f, 1.01338836e-01f, 6.01882580e-02f,
};

#endif  // TFLM_MODEL_SETTINGS_H_
