// Auto-generated by src/models/export_tflm.py. Do not edit.
#ifndef TFLM_MODEL_DATA_H_
#define TFLM_MODEL_DATA_H_

extern const unsigned char g_model[];
extern const unsigned int g_model_len;

#endif  // TFLM_MODEL_DATA_H_
