"""
Export the int8 TFLite model + scaler into C sources for TFLM firmware.
----------------------------------------------------------------------
Reads:
    models/saved/nn_int8.tflite
    models/saved/nn_metadata.json   (written by train_nn.py)

Writes (into firmware/tflm/):
    model_data.h        declaration of the model byte array
    model_data.cc       the model bytes (alignas(16) const unsigned char[])
    model_settings.h    feature count, class labels, and the StandardScaler
                        mean/scale arrays the device applies before inference

The input/output quantization parameters are embedded in the .tflite itself,
so the firmware reads them from the input/output tensors at runtime rather
than hard-coding them here. Only the scaler must be baked in, because we scale
features OUTSIDE the model (see train_nn.py for the rationale).

Usage:
    python src/models/export_tflm.py
"""

import json
import os

MODELS_DIR = os.path.join("models", "saved")
FW_DIR = os.path.join("firmware", "tflm")

TFLITE_PATH = os.path.join(MODELS_DIR, "nn_int8.tflite")
META_PATH = os.path.join(MODELS_DIR, "nn_metadata.json")


def c_float_array(values, per_line=6):
    out, line = [], []
    for v in values:
        line.append(f"{float(v):.8e}f")
        if len(line) == per_line:
            out.append("    " + ", ".join(line) + ",")
            line = []
    if line:
        out.append("    " + ", ".join(line) + ",")
    return "\n".join(out)


def c_byte_array(data, per_line=12):
    out, line = [], []
    for b in data:
        line.append(f"0x{b:02x}")
        if len(line) == per_line:
            out.append("    " + ", ".join(line) + ",")
            line = []
    if line:
        out.append("    " + ", ".join(line) + ",")
    return "\n".join(out)


def main():
    if not os.path.exists(TFLITE_PATH) or not os.path.exists(META_PATH):
        raise SystemExit(
            "Missing model artifacts. Run `python src/models/train_nn.py` first."
        )

    with open(TFLITE_PATH, "rb") as f:
        model_bytes = f.read()
    with open(META_PATH) as f:
        meta = json.load(f)

    os.makedirs(FW_DIR, exist_ok=True)

    feature_names = meta["feature_names"]
    class_names = meta["class_names"]
    mean = meta["scaler_mean"]
    scale = meta["scaler_scale"]
    n_features = len(feature_names)
    n_classes = len(class_names)

    # ---- model_data.h --------------------------------------------------- #
    with open(os.path.join(FW_DIR, "model_data.h"), "w") as f:
        f.write(
            "// Auto-generated by src/models/export_tflm.py. Do not edit.\n"
            "#ifndef TFLM_MODEL_DATA_H_\n#define TFLM_MODEL_DATA_H_\n\n"
            "extern const unsigned char g_model[];\n"
            "extern const unsigned int g_model_len;\n\n"
            "#endif  // TFLM_MODEL_DATA_H_\n"
        )

    # ---- model_data.cc -------------------------------------------------- #
    with open(os.path.join(FW_DIR, "model_data.cc"), "w") as f:
        f.write(
            "// Auto-generated by src/models/export_tflm.py. Do not edit.\n"
            '#include "model_data.h"\n\n'
            "// 16-byte alignment is required by the TFLM tensor allocator.\n"
            "alignas(16) const unsigned char g_model[] = {\n"
        )
        f.write(c_byte_array(model_bytes))
        f.write("\n};\n\n")
        f.write(f"const unsigned int g_model_len = {len(model_bytes)};\n")

    # ---- model_settings.h ----------------------------------------------- #
    labels_c = ",\n".join(f'    "{c}"' for c in class_names)
    features_comment = "\n".join(
        f"//   [{i:2d}] {name}" for i, name in enumerate(feature_names)
    )
    with open(os.path.join(FW_DIR, "model_settings.h"), "w") as f:
        f.write(
            "// Auto-generated by src/models/export_tflm.py. Do not edit.\n"
            "#ifndef TFLM_MODEL_SETTINGS_H_\n#define TFLM_MODEL_SETTINGS_H_\n\n"
            f"constexpr int kFeatureCount = {n_features};\n"
            f"constexpr int kCategoryCount = {n_classes};\n\n"
            "// Tensor arena. This MLP needs only a few KB; tune downward if RAM\n"
            "// is tight (the firmware prints interpreter.arena_used_bytes()).\n"
            "constexpr int kTensorArenaSize = 8 * 1024;\n\n"
            "// Class labels, indexed by the model's output channel.\n"
            "inline const char* const kCategoryLabels[kCategoryCount] = {\n"
            f"{labels_c}\n"
            "};\n\n"
            "// StandardScaler parameters (fit on the training set). The device\n"
            "// computes scaled[i] = (raw[i] - kFeatureMean[i]) / kFeatureScale[i]\n"
            "// BEFORE quantizing and feeding the model. Feature order:\n"
            f"{features_comment}\n"
            "inline const float kFeatureMean[kFeatureCount] = {\n"
        )
        f.write(c_float_array(mean))
        f.write("\n};\n\n")
        f.write("inline const float kFeatureScale[kFeatureCount] = {\n")
        f.write(c_float_array(scale))
        f.write("\n};\n\n#endif  // TFLM_MODEL_SETTINGS_H_\n")

    print("Generated:")
    for name in ("model_data.h", "model_data.cc", "model_settings.h"):
        print(f"  {os.path.join(FW_DIR, name)}")
    print(f"\nModel: {len(model_bytes)} bytes | "
          f"{n_features} features -> {n_classes} classes")
    print(f"int8 test accuracy: {meta.get('int8_test_accuracy', '?')}")


if __name__ == "__main__":
    main()
